subquery/subquery-component-library

components/common/antd.css, components/common/index.tsx, components/common/modal/Modal.module.css, components/common/modal/Modal.stories.tsx, components/common/modal/Modal.tsx, components/common/modal/index.ts, components/common/typography/Typography.tsx
=> feat: modal

components/common/antd.css, components/common/index.tsx, components/common/table/Table.tsx, components/common/tag/Tag.module.css, components/common/tag/Tag.stories.tsx, components/common/tag/Tag.tsx, components/common/tag/index.ts
Changes: 
- feat: table header style 
- feat: theme color update
- feat: add Tag components
=> feat: tag and improvements

components/common/antd.css, components/common/dropdown/Dropdown.module.css, components/common/dropdown/Dropdown.stories.tsx, components/common/dropdown/Dropdown.tsx, components/common/dropdown/index.ts, components/common/index.tsx, components/styles.css
=> feat: add dropdown component

components/app/header/Header.module.css, components/app/header/Header.stories.tsx, components/app/header/Header.tsx, components/app/header/index.ts, components/app/index.tsx, components/common/dropdown/Dropdown.module.css, components/common/dropdown/Dropdown.stories.tsx, components/common/dropdown/Dropdown.tsx, global.d.ts, package.json, tsconfig.json, yarn.lock
=> feat : subquery header

components/app/header/Header.stories.tsx, components/common/address/Address.stories.tsx, components/common/alert/Alert.stories.tsx, components/common/button/Button.stories.tsx, components/common/dialog/Dialog.stories.tsx, components/common/dropdown/Dropdown.stories.tsx, components/common/modal/Modal.stories.tsx, components/common/progressBar/ProgressBar.stories.tsx, components/common/spinner/Spinner.stories.tsx, components/common/table/Table.stories.tsx, components/common/tabs/Tabs.stories.tsx, components/common/tag/Tag.stories.tsx, components/common/textInput/TextInput.stories.tsx, components/common/toast/Toast.stories.tsx, components/common/typography/Typography.stories.tsx
Feat: Add `Doc` `App` `General` folder for clean structure
=> feat: add storybook folder structure

components/app/header/Header.module.css, components/app/header/Header.stories.tsx, components/app/header/Header.tsx, components/common/dropdown/Dropdown.module.css, components/common/dropdown/Dropdown.tsx
[x] Fixed APP dropdown position issue
=> fix: dropdown component position

components/app/header/Header.tsx, components/common/button/AntdButton.tsx, components/common/dropdown/Dropdown.stories.tsx, components/common/dropdown/Dropdown.tsx, package.json, yarn.lock
Ticket: [SQN-1049](https://onfinality.atlassian.net/browse/SQN-1049)
=> update antd version to 5.0.2

.github/workflows/sync.yml
fix auto-merge at release branch
=> feat: fix auto-merge at release branch

components/common/GraphiQL/GraphiQL.stories.tsx, components/common/GraphiQL/GraphiQL.tsx, components/common/GraphiQL/index.ts, components/common/index.tsx, package.json, yarn.lock
Ticket: [SQN-1149](https://onfinality.atlassian.net/browse/SQN-1149)
=> feat: add GraphiQL components

.github/workflows/prerelease.yml, .github/workflows/sync.yml
Ticket: [SQN-1151](https://onfinality.atlassian.net/browse/SQN-1151)
=> feat: enable the release of protected branch

.github/workflows/prerelease.yml
Ticket: [SQN-1151](https://onfinality.atlassian.net/browse/SQN-1151)
=> feat: add repo_token on checkout step

.github/workflows/prerelease.yml
Ticket: [SQN-1151](https://onfinality.atlassian.net/browse/SQN-1151)
=> Add bumped version to package.json

components/common/GraphiQL/GraphiQL.tsx
- fix: pass all props to GraphiQLPlayground
=> fix: pass all props to GraphiQLPlayground

components/common/card/Card.tsx
was unable to have action without dropdown
=> fix card bug

components/app/header/Header.stories.tsx, components/app/header/Header.tsx
Ticket: [#SF-179](https://onfinality.atlassian.net/browse/SF-179)
|  | 
|
=> add linkprops for header logo

components/app/footer/Footer.module.css, components/app/footer/Footer.tsx
Ticket: N/A
| Default | Simple |
|-|-|
|<img width="1507" alt="Screen Shot 2023-03-08 at 3 47 07 PM" src="https://user-images.githubusercontent.com/14360297/223607083-41c0f782-63e0-489d-99b6-02c027a19d59.png">|<img width="1507" alt="Screen Shot 2023-03-08 at 3 39 40 PM" src="https://user-images.githubusercontent.com/14360297/223607192-186a2cb3-c6f0-46d1-a2da-e1b5ed290233.png">|
=> feat: improve Footer component

components/app/footer/Footer.tsx
Ticket: N/A
[x] Improvements: simplified Footer component with a toggle value
=> feat: imporve props for Footer

components/app/footer/Footer.tsx, components/common/button/Button.module.css
=> fix: footer background

components/app/footer/Footer.module.css, components/app/footer/Footer.tsx
update color
|<img width="738" alt="Screen Shot 2023-03-30 at 4 54 45 PM" src="https://user-images.githubusercontent.com/92004774/228724937-4d2b9719-f942-4527-81b0-ad0ba5a2bc97.png">|<img width="911" alt="Screen Shot 2023-03-30 at 5 09 01 PM" …
=> update color to grey700

components/app/footer/Footer.module.css, components/common/card/Card.module.css, components/common/card/Card.stories.tsx, components/common/card/Card.tsx
Ticket: N/A
|Footer|Card|
|-|-|
|<img width="1275" alt="Screen Shot 2023-03-31 at 3 01 28 PM" src="https://user-images.githubusercontent.com/14360297/229004162-506eb624-00a1-4964-9fe1-11c87f2657a8.png">|<img width="1275" alt="Screen Shot 2023-03-31 at 3 01 32 PM" src="https://user-images.githubusercontent.com/14360297/229004239-fc97f363-1f59-4d7f-978e-ad5266d2e1ae.png">|
=> feat:improve Card component

components/app/header/Header.module.css, components/common/button/Button.module.css, components/styles.css, components/utilities/colors.ts, docs/globalStyles/1.colors.stories.mdx
Ticket: N/A
Update theme color 
|theme-color|
|-|
|<img width="1910" alt="Screen Shot 2023-04-19 at 4 27 26 PM" src="https://user-images.githubusercontent.com/14360297/232967126-e9c03c57-e1e8-4c1d-9321-c4ee1fcfa3fb.png">|
=> feat: update theme blue

components/app/header/Header.module.css, components/app/header/Header.tsx, package.json, yarn.lock
Add responsiveness support to Header Component
|Header|
|-|
|<img width="476" alt="Screen Shot 2023-04-26 at 1 47 49 PM" src="https://user-images.githubusercontent.com/14360297/234445274-84e97c90-27ee-4359-be6a-7f84d3e9633c.png">|
=> feat: support responsiveness Header

components/app/header/Header.module.css, components/app/header/Header.stories.tsx, components/app/header/Header.tsx
- Update styles of Header with Logo and RightElement
| update |
|-|
| <img width="479" alt="Screen Shot 2023-04-26 at 3 59 08 PM" src="https://user-images.githubusercontent.com/14360297/234466708-8ab7e0e4-9908-4eb5-9f6d-15eeaee0ce34.png">|
=> feat: imporve Header style with RightElement only

components/app/header/Header.module.css, components/app/header/Header.tsx
- Improve header dropdown styles
=> feat: imporve Header style

components/common/notification/index.ts
Remove scroll bar when the size is enough.
=> fix: notification scroll

components/common/GraphiQL/GraphiQL.stories.tsx, components/common/GraphiQL/GraphiQL.tsx
- Add onQueryResponse on Graphiql.
=> feat: add onQueryResponse callback

components/app/header/Header.tsx
Just change the url to static url.
=> fix: change static files url.

components/app/header/Header.tsx
Just reset router config.
Now will break if installed by npm.
=> feat: reset router config for now

components/app/header/Header.tsx, components/styles.css, yarn.lock
Remove hooks dependency.
Default navigate to use `window.location.replace`, would better to have navigate from outter.
=> feat: remove react-router hooks dependency.

components/common/GraphiQL/GraphiQL.tsx, components/common/GraphiQL/Graphiql-explort.d.ts, package.json, yarn.lock
Upgrade to new version GraphiQL-explorer, old version not working.
Also add `@graphiql/toolkit` in dependency. Phantom dependency in project is not expect.
=> fix: upgrade GraphiQl-explorer

components/app/header/Header.less, components/common/typography/Typography.less, components/styles.css
Ticket: [#ticket number](https://url-for-ticket)
| <img width="1111" alt="0" src="https://user-images.githubusercontent.com/8177474/193933060-b37abd18-c451-4eea-a80f-152410cdd857.png"> | ![1](https://user-images.githubusercontent.com/8177474/193932711-e13b8cd5-e42b-415d-a37f-b98d …
=> feat: dark mode

components/app/header/Header.less, components/app/header/Header.tsx, components/common/dropdown/Dropdown.tsx, components/common/markdown/Markdown.tsx, components/common/markdown/markdown.less, components/common/typography/Typography.less, components/common/typography/Typography.tsx, components/utilities/useBem.ts
- Tiny refactor Header, fix the issue that would re-render unexpected.
- Update preview color, description typograph on Markdown.
=> feat: update Header & Markdown

components/common/checkbox/checkbox.less, components/common/checkbox/checkbox.tsx, components/common/checkbox/index.ts, components/common/index.tsx, components/common/modal/Modal.less, components/common/modal/Modal.module.css, components/common/modal/Modal.tsx
- Refactor Modal.
- Add checkbox.
=> feat: checkbox

components/app/header/Header.tsx
=> feat: custom logo

components/common/address/Addres.less, components/common/address/Address.tsx, components/common/typography/Typography.tsx
Ticket: [#ticket number](https://url-for-ticket)
| <img width="1111" alt="0" src="https://user-images.githubusercontent.com/8177474/193933060-b37abd18-c451-4eea-a80f-152410cdd857.png"> | ![1](https://user-images.githubusercontent.com/8177474/193932711-e13b8cd5-e42b-415d-a37f-b98d …
=> feat: add bigger for address

components/common/markdown/Markdown.tsx, components/common/markdown/markdown.less
- Update markdown style on darkmode.
- Update code/ pre code style on lightmode & darkmode.
=> feat: update markdown style

package.json, yarn.lock
- Change dependencies for bundle.
=> feat: dependency

components/common/markdown/markdown.less
- Change markdown preview title & code font size.
=> feat: adjust markdown

rollup.config.js
=> feat: build cjs version

package.json, rollup.config.js
=> feat: add cjs type

components/common/typography/Typography.less, components/common/typography/Typography.tsx, components/styles.css
- Add more style for typography.
=> feat: enhance typography

components/styles.css
=> feat: add font for futura

components/common/chatUi/chatUi.tsx, components/common/typography/Typography.less, components/common/typography/Typography.tsx, components/styles.css
=> feat: new typography

components/common/typography/Typography.less, components/common/typography/Typography.tsx
=> feat: add shadow for typography

components/common/chatUi/chatUi.tsx
=> chore: link

components/common/chatUi/chatUi.tsx
Ticket: [#ticket number](https://url-for-ticket)
| <img width="1111" alt="0" src="https://user-images.githubusercontent.com/8177474/193933060-b37abd18-c451-4eea-a80f-152410cdd857.png"> | ![1](https://user-images.githubusercontent.com/8177474/193932711-e13b8cd5-e42b-415d-a37f-b98d …
=> chore: callback

components/common/chatUi/chatUi.less, components/common/chatUi/chatUi.tsx, components/utilities/chatWithStream.ts
=> feat: on reaction callback

components/app/subqlHeader/subqlHeader.less
=> fix: popover width
